#include <stdio.h>
#include <limits.h>

#define N 7 // represents the number of days

void print_Cost_Profit(int cost[], int potential_profit[])
{
    printf("Day\tCost\tProfit\n");
    for (int i = 0; i < N; i++)
    {
        printf("%d \t %d \t %d\n", i + 1, cost[i], potential_profit[i]);
    }
    printf("\n");
}

void maxProfit(int cost[])
{
    int min_price = INT_MAX, min_price_index;
    int max_profit = 0, max_profit_index;
    int potential_profit[N];

    for (int i = 0; i < N; i++)
    {
        if (cost[i] < min_price)
        {
            min_price = cost[i];
            min_price_index = i;
            potential_profit[i] = cost[i] - min_price;
        }
        else
        {
            potential_profit[i] = cost[i] - min_price;
            if (potential_profit[i] > max_profit)
            {
                max_profit = potential_profit[i];
                max_profit_index = i;
            }
        }
    }

    print_Cost_Profit(cost, potential_profit);

    printf("So, the maximum profit is generated by buying in day %d and selling in day %d.\n\n", min_price_index + 1, max_profit_index + 1);
}

int main()
{
    int cost[N] = {100, 180, 260, 310, 40, 535, 695};

    maxProfit(cost);

    return 0;
}